import React from 'react';

const BooksList = ({isLoading,books,isloggedIn,deleteBook,dispatch}) => {

// why if not check on array books will got error in browser can not read properties of map coz we define books as array of null
// we can fix by books &&  mean that only if books array filled return it
// check for null like this !books ? null :
// or in the initialState assign to books array to empty array []

  const bookList = books.length > 0 ? books.map((item)=>(   // here check for null .... !books if? false will return null else : will return books.map

        
    <li className='list-group-item d-flex  justify-content-between align-items-center' key={item.id}>
    <div>{item.title}</div>
    <div className='btn-group' role='group'>
      <button type='button' className='btn btn-primary'>
        Read
      </button>
      <button type='button' className='btn btn-danger' disabled={!isloggedIn}  onClick={()=>dispatch(deleteBook(item))

      //The thunks generated by createAsyncThunk will always return a resolved promise with either the fulfilled action object or rejected action object inside, as appropriate.
      // .then((data)=>{   // this promise Result actions  
      //   console.log(data);   // this manner will return object in detail in console
      //   console.log(`return json response object lesson 17...${data}`);  // this manner will return [object object]  in console
      // })
      // will way to handle above and another handle is below


      .unwrap()   // lesson 17
    .then((originalPromiseResult) => {
      // handle result here
      console.log(originalPromiseResult)
    })
    .catch((rejectedValueOrSerializedError) => {
      // handle error here
      console.log(rejectedValueOrSerializedError)
    })
      
      }>
        Delete
      </button>
    </div>
  </li>



  )):"There is no books available";


  return (
    <div>
      <h2>Books List</h2>

     {isLoading ? ('loading...') :     // loading its ok with () or without ()
     
     <ul className='list-group'>{bookList} </ul>
     
     }

    </div>
  );
};

export default BooksList;
